### ISSUE TITLE
A cookie associated with a cross-site resource at https://intercom.io/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by stevecastaneda** [toriihq/gatsby-plugin-intercom-spa#3]
Getting this console error:

`A cookie associated with a cross-site resource at https://intercom.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

`"gatsby-plugin-intercom-spa": "^0.2.0",`

**Comment by berzniz** [comment]
This is related to changes in Chrome - and unrelated to this module:
https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
