### ISSUE TITLE
Question: Does this support Javascript API attributes?

### ISSUE THREAD

**Issue by TatsumiSuenaga** [toriihq/gatsby-plugin-intercom-spa#5]
I tried adding the `background_color` attribute from this [documentation](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects), but it didn't seem to change our messenger background color. 
Does this package currently support that?

Here is my config btw:
```
{
    resolve: 'gatsby-plugin-intercom-spa',
    options: {
      app_id: 'foobar',
      include_in_development: true,
      delay_timeout: 1000,
      background_color: '#EBC853'
    }
}
```

**Comment by daiky00** [comment]
@TatsumiSuenaga you do that in the intercom dashboard not in the app

**Comment by TatsumiSuenaga** [comment]
@daiky00 Thanks! It's been a while, but we realized that as well. Should have closed this a while back haha
